export const siteConfig = {
    global: {
        title: "Point2Learn",
        brandName: "P2L",
        loading: "กำลังโหลด...",
        saving: "กำลังบันทึก...",
        success: "สำเร็จ!",
        error: "เกิดข้อผิดพลาด",
        pointsSuffix: "pt",
    },
    login: {
        headline: "Point2Learn",
        subheadline: "Welcome back! Ready for your next mission?",
        usernamePlaceholder: "Username (e.g., player)",
        passwordPlaceholder: "Password (e.g., love123)",
        loginButton: "Login",
        loginLoading: "Logging in...",
        loginFailed: "Login failed",
        errorDefault: "An error occurred. Please try again.",
    },
    playerDashboard: {
        welcomePrefix: "สวัสดีคนเก่ง วันนี้ทำได้ดีมากครับ!",
        welcomeSuffix: "สู้ๆ กับภารกิจวันนี้ เก็บพอยท์ไปแลกของรางวัลกันน้า",
        accumulatedPoints: "พอยท์สะสมรวม:",
        titlePrefix: "ฉายา:",
        levelPrefix: "Lv.",
        historyLink: "ดูประวัติทั้งหมด",
        sortNewest: "ใหม่ล่าสุด",
        sortOldest: "เก่าสุด",
        sortPointsDesc: "พอยท์ (มากไปน้อย)",
        sortPointsAsc: "พอยท์ (น้อยไปมาก)",
        tasksCategoryPrefix: "หมวดหมู่:",
        submittedPrefix: "ส่งแล้ว",
        timesSuffix: "ครั้ง",
        statusApprovedPaid: "สำเร็จแล้วได้รับพอยท์แล้ว!",
        statusApprovedRepeat: "ส่งได้อีก!",
        statusPending: "รอที่รักชื่นชมผลงานอยู่...",
        statusRejected: "ต้องแก้นิดหน่อย ลองส่งใหม่น้า",
        statusCooldown: "ส่งครบโควต้าแล้ว รอรอบถัดไปน้า",
        btnSubmitFiles: "ส่งรูป/PDF ผลงานเลย!",
        btnSubmitting: "กำลังส่ง...",
        alertSubmitSuccess: "ส่งผลงานเรียบร้อยแล้วค่ะ! รอที่รักตรวจน้า",
        alertSubmitFailed: "เกิดข้อผิดพลาดในการส่งผลงาน",
        approvedCountPrefix: "มี",
        approvedCountSuffix: "ภารกิจที่สำเร็จแล้ว",
    },
    playerStore: {
        headline: "ร้านค้าเปิดแล้ว!",
        subheadline: "ใช้พอยท์ที่สะสมมา แลกของรางวัลสุดพิเศษจากที่รักได้เลย",
        emptyStore: "ตอนนี้ยังไม่มีของรางวัลน้า รอสิ้นเดือนนะคะ",
        btnRedeeming: "กำลังทำรายการ...",
        btnGachaAnimating: "กำลังสุ่ม...",
        btnCooldownWait: "รอสักครู่",
        btnInsufficientPoints: "พอยท์ไม่พอ",
        btnRedeemNormal: "แลกเลย!",
        btnRedeemAngPao: "เปิดซองอั่งเปา!",
        alertRedeemSuccess: "แลกรางวัลสำเร็จ!",
        alertGachaSuccess: "ปิ๊งป๊องงงง! คุณเปิดได้รางวัล... ไปทวงกับที่รักเลย!",
        alertError: "พอยท์ไม่พอ หรือเกิดข้อผิดพลาดค่ะ",
        confirmAngPaoPrefix: "ใช้",
        confirmAngPaoSuffix: "pt เพื่อเปิดซองอั่งเปา 🧧 ใช่ไหมคะ?",
        confirmGachaPrefix: "ใช้",
        confirmGachaSuffix: "pt เพื่อเปิดลุ้นของรางวัลใช่ไหมคะ? 🎲",
        confirmNormalSuffix: "pt ใช่ไหมคะ?",
        itemSpecialBadge: "ไอเทมพิเศษ",
    },
    adminDashboard: {
        headline: "ตรวจผลงาน",
        pendingReview: "รอตรวจ",
        emptyPending: "ยังไม่มีผลงานใหม่ให้ตรวจครับ",
        reviewHistory: "ประวัติการตรวจ",
        submittedByPrefix: "ส่งโดย:",
        btnApprove: "อนุมัติ",
        btnReject: "ปฏิเสธ",
        statusApproved: "อนุมัติแล้ว",
        statusRejected: "ปฏิเสธแล้ว",
        confirmApprove: "คุณแน่ใจว่าต้องการ อนุมัติ งานนี้?",
        confirmReject: "คุณแน่ใจว่าต้องการ ปฏิเสธ งานนี้?",
        alertApproveSuccess: "อนุมัติสำเร็จ ให้พอยท์แล้ว!",
        alertRejectSuccess: "ปฏิเสธงานแล้ว",
        alertError: "เกิดข้อผิดพลาดในการทำรายการ",
    },
    adminStore: {
        headline: "จัดการร้านค้า",
        addRewardHeader: "เพิ่มของรางวัลใหม่",
        formNameLabel: "ชื่อไอเทม/รางวัล (ถ้ามีคำว่า 'สุ่ม' หรือ 'กล่อง' จะมีแอนิเมชันตอนกด)",
        formNamePlaceholder: "ตัวอย่าง: กระเป๋าชาแนล / กล่องสุ่มใจดี",
        formDescLabel: "รายละเอียดเพิ่มเติม (ไม่บังคับ)",
        formDescPlaceholder: "ข้อจำกัดหรือเงื่อนไข...",
        formPointsLabel: "ราคาพอยท์ ที่ต้องใช้แลก",
        formCooldownLabel: "Cooldown คูลดาวน์ต่อชิ้น (นาที)",
        btnAddReward: "เพิ่มไอเทมเข้าร้าน",
        storeItemsHeader: "ไอเทมในร้าน",
        btnEdit: "แก้ไข",
        btnDelete: "ลบ",
        btnSaveEdit: "บันทึกแก้ไข",
        btnCancelEdit: "ยกเลิก",
        emptyStore: "ยังไม่มีไอเทมในร้านครับ",
        alertCreateSuccess: "เพิ่มของรางวัลสำเร็จ!",
        alertUpdateSuccess: "อัปเดตของรางวัลเรียบร้อย",
        alertDeleteSuccess: "ลบของรางวัลแล้ว",
        alertError: "เกิดข้อผิดพลาด กรุณาลองใหม่",
        confirmDeleteSuffix: "ออกจากร้านค้า?",
    }
};
